import json
import re
import requests
import argparse

argParser = argparse.ArgumentParser(
    prog = 'python3 main.py',
    description = 'I can take your makeplace shopping list and tell you where to buy each item from where it\'s cheapest, Yaay',
    epilog = 'Have fun :)')
argParser.add_argument('-c', '--csv', action='store_true', 
                       help="Format output as a CSV")
argParser.add_argument('-w', '--world', 
                       help="The world, data center, or region to retrieve data for. This may be an ID or a name. default is Light")
argParser.add_argument('filename', 
                       help="Name of the shopping list file generated by Makeplace. example: \"save.list.txt\"")

args = argParser.parse_args()

csvOutput = args.csv
world = args.world if args.world else 'Light'
filename = args.filename

itemList = []

def getId(name):
    for id in itemDB:
        if itemDB[id].startswith(name):
            return id
    return None

def getName(id):
    return itemDB[id]

def getCheapest(listings):
    if len(listings) < 1:
        return None
    cheapest = listings[0]
    for list in listings:
        if list['pricePerUnit'] < cheapest['pricePerUnit']:
            cheapest = list['pricePerUnit']
    return cheapest

def getAmount(itemId):
    for item in itemList:
        if item['id'] == itemId:
            return item['amount']
    return 0

with open('items.json') as itemsFile:
    itemDB = json.load(itemsFile)

itemRegx = re.compile(r'^(.+):\s(\d+)$')
sectionRegx = re.compile(r'((.|(?<=.)\n)+=+\n(.|(?<=\w)\n)+)')

### Parse the item list file
with open(filename) as shopListFile:
    shopList = shopListFile.read()
    sections = sectionRegx.findall(shopList)

    sectionName = 'unknown'

    for section in sections:
        section = section[0]
        items = section.splitlines()
        sectionName = items[0].strip()
        if sectionName == 'Furniture (With Dye)':
            continue
        for i in range(2, len(items)):
            match = itemRegx.match(items[i])
            item = {}
            item['item'] = match.group(1)
            item['id'] = getId(match.group(1))
            item['amount'] = int(match.group(2))
            itemList.append(item)

shoppingList = {}

### Get the list of items from the marketboard and filter the cheapest offers
for r in range(0, len(itemList), 100):
    itemIdList = ''
    for i in range(r, min(r+100, len(itemList))):
        itemIdList += itemList[i]['id'] + ','

    resJson = None

    res = requests.get('https://universalis.app/api/v2/' + world +'/' + itemIdList)
    if(res.status_code == 200):
        resJson = res.json()
    else:
        print('HTTP Error: ' + str(res.status_code))
        continue

    for itemId in resJson['items']:
        chp = getCheapest(resJson['items'][itemId]['listings'])
        if not chp:
            resJson['unresolvedItems'].append(itemId)
            continue
        worldName = world if 'worldName' not in chp else chp['worldName']
        chpItem = {}
        chpItem['id'] = str(itemId)
        chpItem['name'] = getName(itemId)
        chpItem['amount'] = getAmount(itemId)
        chpItem['pricePerUnit'] = chp['pricePerUnit']
        chpItem['craftable'] = chp['isCrafted']
        if not worldName in shoppingList:
            shoppingList[worldName] = []
        shoppingList[worldName].append(chpItem)

    if len(resJson['unresolvedItems']) > 0:
        shoppingList['unresolvedItems'] = []
        for itemId in resJson['unresolvedItems']:
            mitem = {}
            mitem['name'] = getName(str(itemId))
            mitem['id'] = str(itemId)
            mitem['pricePerUnit'] = 0
            mitem['craftable'] = 'unknown'
            shoppingList['unresolvedItems'].append(mitem)

### Print the list
if csvOutput:
    print("Item Name,Quantity,P/P,Craftable,Cheapest At")
    for world in shoppingList:
        for item in shoppingList[world]:
            print(item['name'] + "," + str(getAmount(item['id'])) + "," 
                      + str(item['pricePerUnit']) + "," + str(item['craftable']) + "," +world)
else:
    for world in shoppingList:
        print(world + '\n===============')
        for item in shoppingList[world]:
            print(str(getAmount(item['id'])) + "\t" + item['name'] + 
                      "   (Unit price: " + str(item['pricePerUnit']) + ")" + "\tCraftable: " + str(item['craftable']))
        print('\n')
